Models/Sock.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//using GammaWear.Attributes;


namespace GammaWear.Models
{
    public enum SockSize
    {
        [Display(Name = "Extra Small")]
        ExtraSmall,

        [Display(Name = "Small")]
        Small,

        [Display(Name = "Medium")]
        Medium,

        [Display(Name = "Large")]
        Large,

        [Display(Name = "Extra Large")]
        ExtraLarge,

        [Display(Name = "One Size Fits All")]
        OneSizeFitsAll
    }
    public enum ConsumerGroup
    {

        [Display(Name = "Male")]
        Male,
        [Display(Name = "Female")]
        Female,
        [Display(Name = "Kids")]
        Kids,
        [Display(Name = "Unisex")]
        Unisex
    }

    public class Sock
    {
        public int Id { get; set; }
        [Range(0.0, 5.0)]
        public float Rating { get; set; }

        [Required]
        public int MaterialId { get; set; }
        //public Material Material { get; set; }
        [Required]
        public int SockStyleId { get; set; }
        //public SockStyle SockStyle { get; set; }

        [Required]
        public SockSize SockSize { get; set; }

        [Required]
        public int OutdoorSportId { get; set; }
        //public OutdoorSport OutdoorSport { get; set; }

        public ConsumerGroup ConsumerGroup { get; set; }

        [Required]
        public int SeasonId { get; set; }
        //public Season Season { get; set; }
        public int BrandId { get; set; }
        //public Brand Brand { get; set; }
        [Range(1, 1000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public required decimal Price { get; set; }

        // quantity in stock
        [Range(0, int.MaxValue, ErrorMessage = "Quantity must be a non-negative number.")]
        [Display(Name = "In Stock")]
        public int? Quantity { get; set; }
        public string ImageFile { get; set; } = "hs1gayk9.png";
        public string Description { get; set; } = "";

    }



}

Controllers/SockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GammaWear.Data;
using GammaWear.Models;
using GammaWear.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text.RegularExpressions;

namespace GammaWear.Controllers
{
    public class SockController : Controller
    {
        private readonly ILogger<SockController> _logger;
        private readonly GammaWearContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public SockController(ILogger<SockController> logger, GammaWearContext context, IWebHostEnvironment hostingEnvironment)
        {
            _logger = logger;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Sock

        public async Task<IActionResult> Index()
        {
            return View(await _context.Socks.ToListAsync());
            //return _context.Sock != null ?
            //            View(await _context.Sock.ToListAsync()) :
            //            Problem("Entity set 'GammaWearContext.Sock'  is null.");
        }

        // GET: Sock/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var sock = await _context.Socks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sock == null)
            {
                return NotFound();
            }
            var material = await _context.Materials.FirstOrDefaultAsync(m => m.Id == sock.MaterialId);
            var sockStyle = await _context.SockStyles.FirstOrDefaultAsync(s => s.Id == sock.SockStyleId);
            var outdoorSport = await _context.OutdoorSports.FirstOrDefaultAsync(o => o.Id == sock.OutdoorSportId);
            var season = await _context.Seasons.FirstOrDefaultAsync(s => s.Id == sock.SeasonId);
            var brand = await _context.Brands.FirstOrDefaultAsync(b => b.Id == sock.BrandId);

            var viewModel = new SockDetailsViewModel
            {
                Id = sock.Id,
                Rating = sock.Rating,
                MaterialName = material?.Name,
                SockStyleName = sockStyle?.Name,
                OutdoorSportName = outdoorSport?.Name,
                SockSize = sock.SockSize,
                ConsumerGroup = sock.ConsumerGroup,
                SeasonName = season?.Name,
                BrandName = brand?.Name,
                Price = sock.Price,
                Quantity = sock.Quantity,
                ImageFile = sock.ImageFile,
                Description = sock.Description
            };
            return View(viewModel);
        }

        // GET: Sock/Create
        [Authorize(Roles = "Editor")]
        public IActionResult Create()
        {
            _logger.LogInformation("--IActionResult Create: enter");
            PopulateDropDowns();
            return View();
        }

        // POST: Sock/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaterialId,SockStyleId,OutdoorSportId,ConsumerGroup,SeasonId,BrandId,Price,Rating,Quantity,ImageFile,Description")] Sock sock, IFormFile imageFile)
        {
            _logger.LogInformation("--async Task<IActionResult> Create: enter");
            PopulateDropDowns(sock);

            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        _logger.LogWarning($"Validation Error in Create: {error.ErrorMessage}");
                    }
                }
               
                return View(sock);
            }

            // Sanitize Description
            sock.Description = SanitizeInput(sock.Description);

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    sock.ImageFile = await UpdateImage(imageFile, null);
                }

                _context.Add(sock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //PopulateDropDowns();
            return View(sock);
        }
        // GET: Sock/Edit/5
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            _logger.LogInformation("--- async Task<IActionResult> Edit: enter");
            if (id == null)
            {
                return NotFound();
            }

            //var sock = await _context.Socks.FindAsync(id);
            var sock = await _context.Socks
                .FirstOrDefaultAsync(s => s.Id == id);

            if (sock == null)
            {
                return NotFound();
            }
            PopulateDropDowns(sock);
            return View(sock);
        }

        // POST: Sock/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,MaterialId,SockStyleId,OutdoorSportId,ConsumerGroup,SockSize,SeasonId,BrandId,Price,Rating,Quantity,Description")] Sock sock,
            IFormFile imageFile = null)

        {
            if (id != sock.Id)
            {
                _logger.LogInformation("--- Edit with Bind: enter");
                _logger.LogInformation($"--Expect ID:{id}, Actual ID: {sock.Id}");
                return NotFound();
            }

            _logger.LogInformation($"ModelState: {ModelState}");
            _logger.LogInformation($"sock: {sock}");
            _logger.LogInformation($"ModelState.IsValid: {ModelState.IsValid}");

            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        _logger.LogWarning($"Validation Error: {error.ErrorMessage}");
                    }
                }
                PopulateDropDowns(sock);
                return View(sock);
            }

            // Sanitize Description
            sock.Description = SanitizeInput(sock.Description);

            try
            {
                var originalSock = await _context.Socks.AsNoTracking().FirstOrDefaultAsync(s => s.Id == sock.Id);
                if (imageFile != null && imageFile.Length > 0)
                {
                    sock.ImageFile = await UpdateImage(imageFile, originalSock.ImageFile);
                }
                else
                {
                    sock.ImageFile = originalSock.ImageFile;
                }
                _context.Update(sock);
                await _context.SaveChangesAsync();
               
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SockExists(sock.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Details), new { id = sock.Id });

           
        }

        // GET: Sock/Delete/5
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Socks == null)
            {
                return NotFound();
            }

            var sock = await _context.Socks.FirstOrDefaultAsync(m => m.Id == id);
            if (sock == null)
            {
                return NotFound();
            }


            var material = await _context.Materials.FirstOrDefaultAsync(m => m.Id == sock.MaterialId);
            var sockStyle = await _context.SockStyles.FirstOrDefaultAsync(s => s.Id == sock.SockStyleId);
            var outdoorSport = await _context.OutdoorSports.FirstOrDefaultAsync(o => o.Id == sock.OutdoorSportId);
            var season = await _context.Seasons.FirstOrDefaultAsync(s => s.Id == sock.SeasonId);
            var brand = await _context.Brands.FirstOrDefaultAsync(b => b.Id == sock.BrandId);

            var viewModel = new SockDetailsViewModel
            {
                Id = sock.Id,
                MaterialName = material?.Name,
                SockStyleName = sockStyle?.Name,
                OutdoorSportName = outdoorSport?.Name,
                SockSize = sock.SockSize,
                ConsumerGroup = sock.ConsumerGroup,
                SeasonName = season?.Name,
                BrandName = brand?.Name,
                Price = sock.Price,
                Quantity = sock.Quantity,
                ImageFile = sock.ImageFile,
                Description = sock.Description
            };
            return View(viewModel);
        }

        // POST: Sock/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _logger.LogInformation("--- Task<IActionResult> DeleteConfirmed: enter");
            _logger.LogInformation($"--Expect ID:{id}");
            if (_context.Socks == null)
            {

Views/Sock/Create.cshtml
@model GammaWear.Models.Sock

@{
    ViewData["Title"] = "Create Sock";
}

<h1>Create Sock</h1>


<div class="row">
    <div class="col-md-6">
        <img id="imagePreview" src="~/images/default-placeholder.png" class="img-fluid" alt="Sock Image" />
    </div>
    <div class="col-md-6">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="form-group">
                <label for="newImageFile">Upload Image</label>
                <input type="file" name="imageFile" id="newImageFile" class="form-control" onchange="previewImage(event)" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="MaterialId" class="control-label">Material</label>
                <select asp-for="MaterialId" class="form-control" asp-items="ViewBag.Materials">
                    <option value="">- Please select a material -</option>
                </select>
                <span asp-validation-for="MaterialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SockStyleId" class="control-label">SockStyle</label>
                <select asp-for="SockStyleId" class="form-control" asp-items="ViewBag.SockStyles">
                    <option value="">- Please select a Sock Style -</option>
                </select>
                <span asp-validation-for="SockStyleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutdoorSportId" class="control-label">Outdoor Sport</label>
                <select asp-for="OutdoorSportId" class="form-control" asp-items="ViewBag.OutdoorSports">
                    <option value="">- Please select a Outdoor Sport -</option>

                </select>
                <span asp-validation-for="OutdoorSportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConsumerGroup" class="control-label">Consumer Group</label>
                <select asp-for="ConsumerGroup" class="form-control" asp-items="Html.GetEnumSelectList<GammaWear.Models.ConsumerGroup>()">
                    <option value="">- Please select a Consumer Group -</option>
                </select>
                <span asp-validation-for="ConsumerGroup" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="SockSize" class="control-label">Sock Size</label>
                <select asp-for="SockSize" class="form-control" asp-items="Html.GetEnumSelectList<GammaWear.Models.SockSize>()">
                    <option value="">- Please select a Sock Size -</option>
                </select>
                <span asp-validation-for="SockSize" class="text-danger"></span>

            </div>


            <div class="form-group">
                <label asp-for="SeasonId" class="control-label">Season</label>
                <select asp-for="SeasonId" class="form-control" asp-items="ViewBag.Seasons">
                    <option value="">Please select a Season</option>
                </select>
                <span asp-validation-for="SeasonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label">Brand</label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.Brands">
                    <option value="">- Please select a Brand -</option>
                </select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label">Rating</label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

           
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-custom" />
            </div>
        </form>

    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript">
        function previewImage(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('imagePreview');
                output.src = reader.result;
                output.style.display = 'block';
            };
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

Views/Sock/Delete.cshtml
@model GammaWear.ViewModels.SockDetailsViewModel
@using GammaWear.Helpers

@{
    ViewData["Title"] = "Delete Sock";
}

<h1>Delete Sock</h1>

<div>
    
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img class="img-fluid" src="~/images/@Model.ImageFile" alt="@Model.Description">
            </div>

            <div class="col-md-6">

                <p><strong>Material:</strong>  @Model.MaterialName</p>
                <p><strong>Size:</strong> @EnumHelper.GetDisplayName(Model.SockSize)</p>
                <p><strong>Style:</strong> @Model.SockStyleName</p>
                <p><strong>Brand:</strong> @Model.BrandName</p>
                <p><strong>Outdoor Sport:</strong> @Model.OutdoorSportName</p>
                <p><strong>Consumer Group:</strong> @Model.ConsumerGroup</p>
                <p><strong>Season:</strong> @Model.SeasonName</p>
                <p><strong>Price:</strong> @Model.Price.ToString("C")</p>
                <p><strong>In Stock:</strong> @Model.Quantity</p>
                <br />
                <p><strong>Description:</strong>@Model.Description</p>
            </div>
        </div>
        <form id="deleteForm" asp-action="Delete" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="button" value="Delete" class="btn btn-custom" data-toggle="modal" data-target="#deleteModal" />

            <a asp-controller="Home" asp-action="Index" class="btn btn-custom">Home</a>
        </form>
    </div>
</div>

<!-- Modal for delete confirmation -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #6FA5A9;">
                <h5 class="modal-title" id="deleteModalLabel" style="color:white;">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:white;">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this sock?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-custom" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-custom" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $('#confirmDelete').click(function() {
                $('#deleteForm').submit();
            });
        });
    </script>
}

Views/Sock/Details.cshtml
@model GammaWear.ViewModels.SockDetailsViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@using GammaWear.Helpers

<h1>Sock Detail</h1>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid" src="~/images/@Model.ImageFile" alt="@Model.Description">
        </div>
        <div class="col-md-6">
            <p class="d-flex align-items-center">
                <strong>Rating:</strong>
                <span class="ml-2">
                    @for (int i = 1; i <= 5; i++)
                    {
                        if (i <= Math.Floor((double)@Model.Rating))
                        {
                            <span class="fa fa-star star-filled"></span>
                        }
                        else if (i == Math.Ceiling((double)@Model.Rating) && @Model.Rating % 1 != 0)
                        {
                            <span class="fa fa-star-half-alt star-half"></span>
                        }
                        else
                        {
                            <span class="fa fa-star-o star-empty"></span>
                        }
                    }
                </span>
            </p>



            <p><strong>Material:</strong>  @Model.MaterialName</p>
            <p><strong>Size:</strong> @EnumHelper.GetDisplayName(Model.SockSize)</p>
            <p><strong>Style:</strong> @Model.SockStyleName</p>
            <p><strong>Brand:</strong> @Model.BrandName</p>
            <p><strong>Outdoor Sport:</strong> @Model.OutdoorSportName</p>
            <p><strong>Consumer Group:</strong> @Model.ConsumerGroup</p>
            <p><strong>Season:</strong> @Model.SeasonName</p>
            <p><strong>Price:</strong> @Model.Price.ToString("C")</p>
            <p><strong>In Stock:</strong> @Model.Quantity</p>
            <br />
            <p><strong>Description:</strong>@Model.Description</p>
        </div>
        <div>



            <div>
                @if (User.IsInRole("Editor"))
                {
                    <form method="get" asp-action="Create" class="d-inline">
                        <button type="submit" class="btn btn-custom mr-2">Create</button>
                    </form>
                    <form method="get" asp-action="Edit" asp-route-id="@Model.Id" class="d-inline">
                        <button type="submit" class="btn btn-custom mr-2">Edit</button>
                    </form>
                    <form method="get" asp-action="Delete" asp-route-id="@Model.Id" class="d-inline">
                        <button type="submit" class="btn btn-custom mr-2">Delete</button>
                    </form>
                }
                <form method="get" asp-controller="Home" asp-action="Index" class="d-inline">
                    <button type="submit" class="btn btn-custom">Home</button>
                </form>
            </div>

        </div>

    </div>
</div>

Views/Sock/Edit.cshtml
@model GammaWear.Models.Sock

@{
    ViewData["Title"] = "Edit Sock";
}

<h1>Edit Sock</h1>

<div class="row">
    <div class="col-md-6">
        <img id="imagePreview" src="~/images/@Model.ImageFile" class="img-fluid" alt="Sock Image" />
    </div>
    <div class="col-md-6">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label">Current Image</label>
                <input class="form-control" value="@Model.ImageFile" readonly />
                <label for="newImageFile">Upload New Image</label>
                <input type="file" name="imageFile" id="newImageFile" class="form-control" onchange="previewImage(event)" />
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="MaterialId" class="control-label">Material:</label>
                <select asp-for="MaterialId" class="form-control" asp-items="ViewBag.Materials"></select>
            </div>
            <div class="form-group">
                <label asp-for="SockStyleId" class="control-label">Style:</label>
                <select asp-for="SockStyleId" class="form-control" asp-items="ViewBag.SockStyles"></select>
            </div>
            <div class="form-group">
                <label asp-for="OutdoorSportId" class="control-label">Outdoor Sport:</label>
                <select asp-for="OutdoorSportId" class="form-control" asp-items="ViewBag.OutdoorSports"></select>
            </div>
            <div class="form-group">
                <label asp-for="ConsumerGroup" class="control-label">Consumer Group:</label>
                <select asp-for="ConsumerGroup" class="form-control" asp-items="Html.GetEnumSelectList<GammaWear.Models.ConsumerGroup>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="SockSize" class="control-label">Size:</label>
                <select asp-for="SockSize" class="form-control" asp-items="Html.GetEnumSelectList<GammaWear.Models.SockSize>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="SeasonId" class="control-label">Season:</label>
                <select asp-for="SeasonId" class="form-control" asp-items="ViewBag.Seasons"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.Brands"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Price:</label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label">Rating:</label>
                <input asp-for="Rating" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">In Stock:</label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description:</label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-custom" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Sock" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-custom">Detail</a>
    <a asp-controller="Home" asp-action="Index" class="btn btn-custom">Home</a>
    <br />
</div>

@section Scripts {
    <script type="text/javascript">
        function previewImage(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('imagePreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

Views/Sock/Index.cshtml
@model IEnumerable<GammaWear.Models.Sock>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<div class="row">
    @await Html.PartialAsync("_SockList", Model)
</div>